#!/usr/bin/python

import os
import sys
import smtplib
from email import Encoders
from email import MIMEBase
from email import MIMEMultipart
from email import MIMEText
from optparse import OptionParser
from datetime import date

parser = OptionParser()
parser.header = {}
parser.add_option('-s', '--dbgap_studies', action='store', dest='dbgap_studies', type='int', help='Number of dbGaP studies')
parser.add_option('-v', '--dbgap_variables', action='store', dest='dbgap_variables', type='int', help='Number of dbGaP variables')
parser.add_option('-p', '--dbgap_page_studies', action='store', dest='dbgap_page_studies', type='int', help='Number of PAGE studies')
parser.add_option('-n', '--dbgap_page_variables', action='store', dest='dbgap_page_variables', type='int', help='Number of PAGE variables')
parser.add_option('-d', '--pfindr_home', action='store', dest='pfindr_home', type='string', help='The pfindr HOME directory')

(options, args) = parser.parse_args()

dbgap_studies=0
dbgap_variables=0
dbgap_page_studies=0
dbgap_page_variables=0
pfindr_home='/pfindr/users/pfindr'

if options.dbgap_studies:
    dbgap_studies=options.dbgap_studies
    
if options.dbgap_variables:
    dbgap_variables=options.dbgap_variables
    
if options.dbgap_page_studies:
    dbgap_page_studies=options.dbgap_page_studies
    
if options.dbgap_page_variables:
    dbgap_page_variables=options.dbgap_page_variables
    
if options.pfindr_home:
    pfindr_home=options.pfindr_home
    
mail_footer = 'Do not reply to this message.  This is an automated message generated by the system, which does not receive email messages.'

_base_mail = """
As of the today %(today)s updates, there are:

dbGaP studies: %(dbgap_studies)d
dbGaP variables: %(dbgap_variables)d
PAGE studies: %(dbgap_page_studies)d
PAGE variables: %(dbgap_page_variables)d

The attached zip file contains:
    - the current dbGaP/PAGE studies with the number of variables
    - the differences from the previous update

"""
outer = MIMEMultipart.MIMEMultipart()
outer['Subject'] = 'PhenoExplorer Update'
outer['From'] = 'PhenoExplorer Online Notification <no_reply@example.org>'
outer['To'] = 'ambite@isi.edu,serban@isi.edu,tallis@isi.edu'

msg = MIMEText.MIMEText('%s\n\n\n\n%s' % (_base_mail % (dict(dbgap_studies=dbgap_studies, dbgap_variables=dbgap_variables, dbgap_page_studies=dbgap_page_studies, dbgap_page_variables=dbgap_page_variables, today=date.today())), mail_footer), 'plain')
outer.attach(msg)

fp = open('%s/update_dbgap.zip' % pfindr_home, 'rb')
msg = MIMEBase.MIMEBase('application', 'octet-stream')
msg.set_payload(fp.read())
fp.close()
Encoders.encode_base64(msg)
msg.add_header('Content-Disposition', 'attachment', filename='update_dbgap.zip')
outer.attach(msg)

s = smtplib.SMTP('smtp.isi.edu')
s.sendmail('PhenoExplorer Online Notification <no_reply@phenoexplorer.org>', outer['To'].split(','), outer.as_string())
s.quit()

